// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skudfjlugxvepumihkap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdWRmamx1Z3h2ZXB1bWloa2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjU1MzAsImV4cCI6MjA1OTMwMTUzMH0.tOyAUyO6Bt1RfmUkuchRNl-zTLzmJB6UYcD_eaY_ttA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);